### ISSUE TITLE
Option to merge successive variable declarations back into a single declaration?

### ISSUE THREAD

**Issue by mcandre** [twolfson/esformatter-var-each#7]
Hi,

Could we get an option to do the opposite, so that multiple declarations in a row are merged back into a single declaration?

**Comment by twolfson** [comment]
It is possible but I'd prefer it lives in another repo (e.g. fork and write `esformatter-var`). `esformatter` ecosystem growth has more/less halted since this was written so I'd prefer to not pick up extra work to maintain without much people gaining value from it

One alternative is to use a library like ESLint which has `--fix` support for such behavior:

https://eslint.org/docs/rules/one-var
